@startuml
actor Operator
participant MES_UI
participant CRM
participant MES_API
database Cache
database DB

group Получение списка свободных заказов
  Operator -> MES_UI  : Зашел в систему
  MES_UI -> MES_API   : Открытие первой страницы
  MES_API -> Cache    : Запрос списка заказов из кэша
  MES_API <- Cache    : Список из кэша
  MES_UI <- MES_API   : Ответ со списком заказов
  Operator <- MES_UI  : Отображение дашборда
end

group Взятие в работу
  Operator -> MES_UI  : Принял заказ в работу
  MES_UI -> MES_API   : Переход заказа в статус MANUFACTURING_STARTED
  MES_API -> Cache    : Обновление кэша
  Cache -> DB         : Обновление записи в БД
  Cache <- DB         : Ответ
  MES_API <- Cache    : Ответ
  MES_UI <- MES_API   : Ответ
  Operator <- MES_UI  : Ответ
end

group Подтверждение заказа
  CRM -> MES_API: Сообщение об изменении статуса на MANUFACTURING_APPROVED
  MES_API -> Cache: Обновление кэша
  Cache -> DB         : Обновление записи в БД
  Cache <- DB         : Ответ
  MES_API <- Cache    : Ответ
  CRM <- MES_API  : Ответ
end
@enduml